main:file.o function.o login.o menu.o menu_m.o Mygets.o main.o
	gcc file.o function.o login.o menu.o menu_m.o Mygets.o main.o -o main
file.o:file.c
	gcc -c file.c -o file.o
function.o:function.c
	gcc -c function.c -o function.o
login.o:login.c
	gcc -c login.c -o login.o
menu.o:menu.c
	gcc -c menu.c -o menu.o
menu_m.o:menu_m.c
	gcc -c menu_m.c  -o menu_m.o
Mygets.o:Mygets.c
	gcc -c Mygets.c -o Mygets.o


